### ISSUE TITLE
problem with jestream:  Unable to locate a class or view for component [jet-application-logo]

### ISSUE THREAD

**Issue by ivanomatteo** [imanghafoori1/laravel-microscope#100]
laravel 8 + jetstream with inertiajs and teams 
```
  Unable to locate a class or view for component [jet-application-logo].

  at vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php:275
    271▕         if ($viewFactory->exists($view = $this->guessViewName($component))) {
    272▕             return $view;
    273▕         }
    274▕ 
  ➜ 275▕         throw new InvalidArgumentException(
    276▕             "Unable to locate a class or view for component [{$component}]."
    277▕         );
    278▕     }
    279▕ 
```

**Comment by imanghafoori1** [comment]
Thanks for the report, please verify that <jet-application-logo> tag can and will do work properly.
I think there is some problem with that.

Also, mention exactly how to reproduce the error.

**Comment by ivanomatteo** [comment]
It’s a official component from jet stream.
Just Install Laravel 8 with jet stream + inertia + teams

**Comment by imanghafoori1** [comment]
I think you should be ok with the latest version. v1.0.148

**Comment by AlexioVay** [comment]
Where is the actual definition that for example `<x-jet-label>` refers to a view file inside the vendor folder? I couldn't find it and I want to modify it. I have the same error message but I am using my own components mainly with some expections that still refer to Jetstream components that I want to replace completely.
