### ISSUE TITLE
Checking imports - ErrorException

### ISSUE THREAD

**Issue by abbasmashaddy72** [imanghafoori1/laravel-microscope#106]
**Don't know what the issue is Please Help me out.**

Undefined array key "App\Services\BaseService"

  at vendor/imanghafoori/laravel-microscope/src/Analyzers/ParseUseStatement.php:17
     13▕ 
     14▕             self::$cache = self::parseUseStatements(token_get_all($code), $namespacedClassName)[0] + self::$cache;
     15▕         }
     16▕ 
  ➜  17▕         return self::$cache[$namespacedClassName];
     18▕     }
     19▕ 
     20▕     public static function findClassReferences(&$tokens, $absFilePath)
     21▕     {

      +30 vendor frames 
  31  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Below is the Attachment is the  PHP File where I am having the error.**

[BaseService (copy).txt](https://github.com/imanghafoori1/laravel-microscope/files/6251023/BaseService.copy.txt)

**Comment by imanghafoori1** [comment]
Please mention the exact php version and command you have run.

**Comment by abbasmashaddy72** [comment]
laravel 8 with php 8

**Comment by imanghafoori1** [comment]
We do not support php 8 yet.

**Comment by abbasmashaddy72** [comment]
Okay Thnaks Bro

**Comment by imanghafoori1** [comment]
You can now install dev-master version for PHP 8.0.x
not fully tested but it should work.

**Comment by ricklambrechts** [comment]
Hi,

Tried the microscope package in our project today. 
Only the `check:imports` is still not working with PHP 8 and Laravel 8.

Getting the same error as above, but with a different class `Undefined array key "App\Policies\TeamPolicy"`.

**Comment by imanghafoori1** [comment]
will take a look at it.

**Comment by imanghafoori1** [comment]
@ricklambrechts 
You can enjoy php8 support in the latest version.
