### ISSUE TITLE
Can you add a disable for when not in use. 

### ISSUE THREAD

**Issue by ap-coder** [imanghafoori1/laravel-microscope#108]
add one to your config that can be used in .env 

Seems like a dumb thing but would be really helpful for some. 

Something similar to.
//config/microscope.php
	'enabled' => env('MICROSCOPE_ENABLED', true),

//.env
MICROSCOPE_ENABLED=true

**Comment by imanghafoori1** [comment]
Please describe why do you need it?
what is the real problem you have encountered?

**Comment by ap-coder** [comment]
No problems but i run a team of developers that would run them just to see what they do. I like to use the tool sometimes but other times i would like to deactivate it from the artisan commands without removing it. That way the other developers that do not run our source control are not changing all those files when its not needed.  

Maybe you could even add a logged in user specific  switch as well as the other option i asked about.  Both telescope and debugbar have the option to have it enabled or disabled. 

I manually created the user specific option for telescope in our application. Both are very helpful at times. 

Anyway does that answer why it would be a great asset to your helpful package.

**Comment by imanghafoori1** [comment]
This differs from the Telescope, since it is only enabled only on the command line mode of laravel. (Not for regular HTTP requests.)
Other team members should not run a command that they are not supposed to.

**Comment by ap-coder** [comment]
ok no worries ill just remove it. thanks

**Comment by Oxicode** [comment]
Good idea @ap-coder

**Comment by imanghafoori1** [comment]
Anyway if you see a real need, you can send a PR for that feature

**Comment by imanghafoori1** [comment]
ok I will add that real quick

**Comment by imanghafoori1** [comment]
this is now implemented in the latest version
