### ISSUE TITLE
php artisan check:all have ErrorException Undefined variable: body 

### ISSUE THREAD

**Issue by apiruknetway** [imanghafoori1/laravel-microscope#109]
When run
php artisan check:all

Checking dd...
 - Finished looking for debug functions. (730 files checked)
Checking for route-less controllers...

   ErrorException 

  Undefined variable: body

  at vendor/imanghafoori/laravel-microscope/src/Analyzers/ClassMethods.php:65
     61▕             $methods[] = [
     62▕                 'name' => $name,
     63▕                 'visibility' => $visibility,
     64▕                 'signature' => $signature,
  ➜  65▕                 'body' => Refactor::toString($body),
     66▕                 'startBodyIndex' => [$charIndex, $i],
     67▕                 'returnType' => $returnType,
     68▕ 
     69▕             ];

**Comment by imanghafoori1** [comment]
Hi,
please also mention you exact version of PHP in cli.
and if you can provide the code which has caused the error.

**Comment by imanghafoori1** [comment]
Could you please try out the dev-master version?
it should be ok.
