### ISSUE TITLE
Problem With "Constructor property promotion" PHP8

### ISSUE THREAD

**Issue by karakhanyans** [imanghafoori1/laravel-microscope#125]
In my class, I've used Constructor Property Promotion, and when I do check:all, command says for example 
`privateUserId` class not found

Constructor example:
```
public function __construct(private UserId $id, private UserEmail $email, private UserNickname $nickname)
    {
    }

**Comment by imanghafoori1** [comment]
Support for php8 is not granted and I am slowly improving it.

**Comment by karakhanyans** [comment]
That's great! Waiting for it.

**Comment by imanghafoori1** [comment]
@karakhanyans Could you please try the dev-master version to see if it works.
After you confirm the fix, release it as a patch version.
