### ISSUE TITLE
Wrong Namespace Suggestion

### ISSUE THREAD

**Issue by karakhanyans** [imanghafoori1/laravel-microscope#126]
My namespace is .../Mappers, plugin suggests changing it to MAppers

```
 1 Incorrect namespace: namespace App\Infrastructure\Business\Shared\User\DataMappers;             |
at app/Infrastructure/Business/Shared/User/DataMappers/UserAccountDataMapper.php:3                   |

 Do you want to change it to: App\Infrastructure\Business\Shared\User\DataMAppers

**Comment by imanghafoori1** [comment]
could you please mention your 
OS
php-cli
microscope version

Thanks a lot

**Comment by karakhanyans** [comment]
Microscope: 1.0.163
OS: MacOS BigSur 11.4
PHP 8.0

**Comment by imanghafoori1** [comment]
I am curious if there is any special (invisible) characters in the folder name "DataMapper"
Could you please rename the folder and have a quick test again.
Since there should be no logical reason for the microscope to be interested in letter "A" of  the word "DataMapper"

**Comment by karakhanyans** [comment]
Actually it's not inserting word A, it's capitalizing it, I think the microscope thinks about word Mapper as word App with lower case that why wanted to capitalize it.

**Comment by imanghafoori1** [comment]
Yeah, that is an smart guess.
Will check it.

**Comment by imanghafoori1** [comment]
Check out the latest patch, it should be fixed.
