### ISSUE TITLE
No route is defined for controller action - bug or feature

### ISSUE THREAD

**Issue by rabol** [imanghafoori1/laravel-microscope#127]
First, the package is awesome!

I'm using Cashier in my app and one thing that one can do to add functionality to handle extra web hooks is to overwrite the cashier route, as per the documentation: https://laravel.com/docs/8.x/billing#defining-webhook-event-handlers

However, that triggers an error in laravel-microscope
```
 31 No route is defined for controller action:                                                         |
|  App\Http\Controllers\WebHookController@handleCheckoutSessionCompleted                                |
at app/Http/Controllers/WebHookController.php:13  
```

**Comment by imanghafoori1** [comment]
Thanks the report
These are just warning for the user investigate and decide on.
If you know that is ok you may just ignore that warning.
But anyway I keep that in mind may be I can make microscope more smart in future.

Good luck
