### ISSUE TITLE
Package changed my code!

### ISSUE THREAD

**Issue by babakmoeinifar** [imanghafoori1/laravel-microscope#13]
**When I ran this command:**

 _php artisan check:psr4_ 

**then my code changed to this:**

namespace App\Providers;
use Illuminate\Support\ServiceProvider;

namespace App\Providers;
{

    public function register()
    {
namespace App\Providers;
namespace App\Providers;
        });
    }

    public function boot()
    {
namespace App\Providers;
        $this->publishes([
            __DIR__ . '/migrations' => database_path('/migrations'),
            __DIR__ . '/views' => base_path('/resources/views/bank'),
            __DIR__ . '/config' => config_path(),
        ]);
    }
}

**Comment by babakmoeinifar** [comment]
**my code was:**
`
<?php
namespace Payment;
use Illuminate\Support\ServiceProvider;

class PaymentServiceProvider extends ServiceProvider
{

    public function register()
    {
        $this->app->bind('payment', function () {
            return new Payment();
        });
    }

    public function boot()
    {
        $this->loadViewsFrom(__DIR__ . '/views', 'payment');
        $this->publishes([
            __DIR__ . '/migrations' => database_path('/migrations'),
            __DIR__ . '/views' => base_path('/resources/views/bank'),
            __DIR__ . '/config' => config_path(),
        ]);
    }
}
`

**I ran this command:**
`
 _php artisan check:psr4_ 
`
**then my code changed to this:**
`
<?php
namespace App\Providers;
use Illuminate\Support\ServiceProvider;

namespace App\Providers;
{

    public function register()
    {
namespace App\Providers;
namespace App\Providers;
        });
    }

    public function boot()
    {
namespace App\Providers;
        $this->publishes([
            __DIR__ . '/migrations' => database_path('/migrations'),
            __DIR__ . '/views' => base_path('/resources/views/bank'),
            __DIR__ . '/config' => config_path(),
        ]);
    }
}

`

**Comment by imanghafoori1** [comment]
Please provide screen shots of the before and after

And please mention the exact version number of microscope

**Comment by babakmoeinifar** [comment]
<?php
/**
 * Created by PhpStorm.
 * User: mostafa
 * Date: 09/09/2018
 * Time: 02:58 AM
 */

namespace Payment;


use Illuminate\Support\ServiceProvider;

class PaymentServiceProvider extends ServiceProvider
{

    public function register()
    {
        $this->app->bind('payment', function () {
            return new Payment();
        });
    }

    public function boot()
    {
        $this->loadViewsFrom(__DIR__ . '/views', 'payment');
        $this->publishes([
            __DIR__ . '/migrations' => database_path('/migrations'),
            __DIR__ . '/views' => base_path('/resources/views/bank'),
            __DIR__ . '/config' => config_path(),
        ]);
    }
}

// First File
