### ISSUE TITLE
Out of memory when using check:routes

### ISSUE THREAD

**Issue by longestdrive** [imanghafoori1/laravel-microscope#135]
Hi
Just trying this package and tried running `php artisan check:routes` and it came up with an out of memory error: (note package installed correctly)

```
Checking route definitions...
 - 121 Route:: definitions were checked. (0 skipped)
Checking route names exists...

mmap() failed: [12] Cannot allocate memory

PHP Fatal error:  Out of memory (allocated 1107300352) (tried to allocate 2147483656 bytes) in /home/vagrant/code/wedleague/vendor/imanghafoori/laravel-microscope/src/Analyzers/FunctionCall.php on line 139
PHP Stack trace:
```

In my php.ini file I have:
```
; Maximum amount of memory a script may consume
; http://php.net/memory-limit
memory_limit = -1
```
Which I think means the script can use unlimited memory

Is it expected to use so much memory?

Thank you

**Comment by imanghafoori1** [comment]
No in fact it should do its job with very little memory.
I think it is stuck in an infinite loop.
Please provide your:
PHP version
microscope version
OS
and the content of your route files if possible.

**Comment by longestdrive** [comment]
HI - thanks for coming back:
php version 7.4.5
microscope: 1.0.165 
OS windows 10 but running on a vagrant machine using homestead

Attaching routes as a zip file - 
[routes.zip](https://github.com/imanghafoori1/laravel-microscope/files/6646385/routes.zip)

Thank you

**Comment by imanghafoori1** [comment]
it seems that the problem is somewhere in your blade files.
to discover the problematic files:
1- commit all your blade files.
2- delete them folder by folder, and run `php artisan check:routes` each time you delete a folder.
3- once you see that the problem is gone, recover your files using git.
4- please send me the latest folder you deleted.

hopefully the error is in views folder. otherwise you should look in app folder.

**Comment by longestdrive** [comment]
Hi
Ok - I've just worked through the view files and narrowed it down to one file which contained a typo relating to the route:

```
<p><a href="{{route('home)}}">www.{{config('site.brand_url')}}</a></p>
```

Which should have been:
```
<p><a href="{{route('home')}}">www.{{config('site.brand_url')}}</a></p>
```

Thank you for helping me track the error - is there a way of logging in the package to check progress or the fail points?

Thanks again

**Comment by imanghafoori1** [comment]
We assumed a correct syntax, but I will try to handle these situations more gracefully.

**Comment by imanghafoori1** [comment]
this is now fixed in the latest patch version.
