### ISSUE TITLE
Annotations by PhpStorm get flagged as not existing

### ISSUE THREAD

**Issue by hypnotox** [imanghafoori1/laravel-microscope#139]
When running the import checker it writes the following error:

`use JetBrains\PhpStorm\ArrayShape;  <==== does not exist`

I'm guessing this has to do with them not being "real" in the sense of existing in the project files scope.
Since they do not harm the application in any way, i think it would be safe to accept imports from the `\JetBrains\PhpStorm` namespace by default or make a list of existing annotations.

These are the current ones:
- ArrayShape
- Deprecated
- ExpectedValues
- Immutable
- Language
- NoReturn
- Pure

Cheers.

**Comment by imanghafoori1** [comment]
Please give me a sample code or a documentation link, about these.
since I have never seen them.

**Comment by imanghafoori1** [comment]
https://github.com/JetBrains/phpstorm-attributes

If you are using other static analysis tools and don’t want to get Class not found issues, then you might want to add the attributes package to your composer.json as a dev dependency:

composer require --dev jetbrains/phpstorm-attributes
