### ISSUE TITLE
checkEndIf incorrect warning

### ISSUE THREAD

**Issue by akosglue** [imanghafoori1/laravel-microscope#141]
when running `php artisan check:endif` I get the info: Checking for Early Returns...

I think it is because the message is wrong here:
https://github.com/imanghafoori1/laravel-microscope/blob/ec1f4e04c5d98a7870665cae905cdc001b5ebebe/src/Commands/CheckEndIf.php#L85

**Comment by imanghafoori1** [comment]
yeah, since it is copy/pasted at the start.
I can fix it myself but would be happier to accept a PR from you. fir it at : `Commands/CheckEndif:85`
