### ISSUE TITLE
action_comments doesn't support multiple routes to same method

### ISSUE THREAD

**Issue by beard7** [imanghafoori1/laravel-microscope#144]
It may be too much hassle, but it would be helpful if action_comments could be generated for multiple routes that point to the same method.

I've got quite a few methods that return different data depending on the route that was used to access them -- maybe applying an additional filter if a particular route is used, for example.

Showing all the routes that point to the method would be great.

**Comment by imanghafoori1** [comment]
hummmm, yeah this is something that I have not thought about.

**Comment by imanghafoori1** [comment]
It is supported as of `v1.0.247`
