### ISSUE TITLE
Fails To Install

### ISSUE THREAD

**Issue by HDVinnie** [imanghafoori1/laravel-microscope#146]
```
Using version ^1.0 for imanghafoori/laravel-microscope
./composer.json has been updated
Running composer update imanghafoori/laravel-microscope
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking imanghafoori/laravel-microscope (v1.0.180)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading imanghafoori/laravel-microscope (v1.0.180)
  - Installing imanghafoori/laravel-microscope (v1.0.180): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   TypeError 

  is_dir(): Argument #1 ($filename) must be of type string, array given

  at vendor/imanghafoori/laravel-microscope/src/SpyClasses/SpyRouter.php:56
     52▕             $err = "['middlewares' => ...] key passed to Route::group(...) is not correct.";
     53▕             $this->routeError($info, $err, "Incorrect 'middlewares' key.");
     54▕         }
     55▕ 
  ➜  56▕         if ($ns && isset($attributes['namespace']) && ! is_dir($dir) && \str_replace(['\\', '/'], DIRECTORY_SEPARATOR, $ns) !== $dir) {
     57▕             $err = "['namespace' => "."'".$attributes['namespace'].'\'] passed to Route::group(...) is not correct.';
     58▕             $this->routeError($info, $err, 'Incorrect namespace.');
     59▕         }
     60▕     }

      +30 vendor frames 
  31  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

      +5 vendor frames 
  37  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by imanghafoori1** [comment]
@HDVinnie Could you please send me your route files?
It seems you have a special type of using `Route:group` which I have not considered.

**Comment by HDVinnie** [comment]
@imanghafoori1 https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/routes/web.php

**Comment by imanghafoori1** [comment]
@HDVinnie I installed microscope on the master branch of your repository.
Please make sure the error has happened on master branch.
If it is on some other branch, tell me.

**Comment by HDVinnie** [comment]
It seems hit or miss but when it happens it seems related to a package I use....this file specifically.

https://github.com/ARCANEDEV/LogViewer/blob/master/src/Http/Routes/LogViewerRoute.php

Stack:
`
stacktrace] #0 /var/www/html/vendor/imanghafoori/laravel-microscope/src/SpyClasses/SpyRouter.php(56): is_dir() #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(377): Imanghafoori\\LaravelMicroscope\\SpyClasses\\SpyRouter->updateGroupStack() #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Routing\\Router->group() #3 /var/www/html/vendor/arcanedev/support/src/Routing/RouteRegistrar.php(64): Arcanedev\\Support\\Routing\\RouteRegistrar->forwardCallTo() #4 /var/www/html/vendor/arcanedev/support/src/Routing/RouteRegistrar.php(49): Arcanedev\\Support\\Routing\\RouteRegistrar->forwardCallToRouter() #5 /var/www/html/vendor/arcanedev/log-viewer/src/Http/Routes/LogViewerRoute.php(36): Arcanedev\\Support\\Routing\\RouteRegistrar->__call() #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Arcanedev\\LogViewer\\Http\\Routes\\LogViewerRoute->map() #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}() #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure() #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod() #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(66): Illuminate\\Container\\BoundMethod::call() #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): Illuminate\\Container\\BoundMethod::callClass() #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call() #13 /var/www/html/vendor/arcanedev/support/src/Routing/Concerns/RegistersRouteClasses.php(28): Illuminate\\Container\\Container->call() #14 /var/www/html/vendor/arcanedev/log-viewer/src/Providers/RouteServiceProvider.php(44): Arcanedev\\Support\\Providers\\RouteServiceProvider::mapRouteClasses() #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Arcanedev\\LogViewer\\Providers\\RouteServiceProvider->Arcanedev\\LogViewer\\Providers\\{closure}() #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}() #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure() #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod() #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call() #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(120): Illuminate\\Container\\Container->call() #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(45): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->loadRoutes() #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider->Illuminate\\Foundation\\Support\\Providers\\{closure}() #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}() #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\\Container\\Util::unwrapIfClosure() #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod() #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call() #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(113): Illuminate\\Container\\Container->call() #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(917): Illuminate\\Support\\ServiceProvider->callBootedCallbacks() #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(895): Illuminate\\Foundation\\Application->bootProvider() #30 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}() #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(896): array_walk() #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot() #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap() #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith() #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap() #36 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle() #37 {main} "}
`

**Comment by imanghafoori1** [comment]
I think you should also send the log viewer config file. since the route configuration is read from there.

**Comment by imanghafoori1** [comment]
It seems that the problem is with log-viewer package.
the namespace of the routes must be a string, not an array.

Anyway, it seems to be ok with the `Laravel Framework 8.48.2`.
I think you have an older version.

**Comment by HDVinnie** [comment]
Im on `v8.49.2`. Either way I'll just use this for `dev` purposes and remove the log-viewer package while using this package. Thanks.

**Comment by imanghafoori1** [comment]
you can just change the line 55 of config/log-viewer.php from `'namespace'  => ['Staff'],` to    ` 'namespace'  => 'Staff',`
but anyways I wrap the whole thing in a try/catch to avoid hard crashing.

**Comment by HDVinnie** [comment]
@imanghafoori1 cheers. Thanks for your time.
