### ISSUE TITLE
Class does not exist & Wrong import

### ISSUE THREAD

**Issue by khodemobin** [imanghafoori1/laravel-microscope#153]
Wrong import error for phpstorm types like JetBrains\PhpStorm\Pure , JetBrains\PhpStorm\ArrayShape.
Class does not exist for mixed type.

**Comment by imanghafoori1** [comment]
Take a look at: https://github.com/imanghafoori1/laravel-microscope/issues/139

**Comment by khodemobin** [comment]
and what about type mixed?

**Comment by imanghafoori1** [comment]
I will fix that, thanks for the report.
