### ISSUE TITLE
Class not detected if declared in same file

### ISSUE THREAD

**Issue by melicerte** [imanghafoori1/laravel-microscope#160]
When launching `php artisan check:imports` on the following code:
```
<?php
namespace Toto;

class Super {
}

class Amazing {
  private Super $super;

  public function __construct() {
    $this->super = new Super();
  }
}
```

the following error is displayed:
`Class does not exist:
  Toto\Super at Toto/Amazing.php:11
`

whereas I expect that the class Super should be detected.

**Comment by melicerte** [comment]
Yes it works perfectly in practice :)

**Comment by imanghafoori1** [comment]
I think this is not a standard form of defining classes.
seemingly you have to use an anonymous class instead of defining two classes in a file.

**Comment by melicerte** [comment]
Since PHP allows it, it should be supported imho

**Comment by imanghafoori1** [comment]
I like to support it if I find a way of doing it. But anyway, it is not promised to support non-psr4 things.

**Comment by imanghafoori1** [comment]
I keep this in mind, thanks for reporting.

**Comment by imanghafoori1** [comment]
@melicerte Now we support it.
I found the solution.

**Comment by melicerte** [comment]
Thanks @imanghafoori1 !
