### ISSUE TITLE
check specific directory 

### ISSUE THREAD

**Issue by alirezadp10** [imanghafoori1/laravel-microscope#166]
How can I run the check command on the specifics directory?

**Comment by imanghafoori1** [comment]
currently you can not

**Comment by alikhosravidev** [comment]
Hello,
@alirezadp10 
If you do not want to add this feature I can do it.

**Comment by imanghafoori1** [comment]
ghaboole, do it.

**Comment by alikhosravidev** [comment]
Thanks, I start today.

**Comment by imanghafoori1** [comment]
You can use `--file=` and `--folder=` now.
