### ISSUE TITLE
Command missing on testing environment

### ISSUE THREAD

**Issue by ALTELMA** [imanghafoori1/laravel-microscope#167]
I was trying to config this package on the CI process to verify code before deployment. I saw something strange when running in testing all of the artisan command missing. Why?

Could you please suggest to me how to set up it in a testing environment?

**Comment by imanghafoori1** [comment]
this package is set to avoid stepping in when you are running tests.

https://github.com/imanghafoori1/laravel-microscope/blob/977e5178029bf0217326790315a88ed0d2acc058/src/LaravelMicroscopeServiceProvider.php#L182

you can change the env variable before running microscope
