### ISSUE TITLE
check env not working correctly wit nWidart/laravel-modules

### ISSUE THREAD

**Issue by hooman-mirghasemi** [imanghafoori1/laravel-microscope#168]
Hi
I am using  this package:
https://github.com/nWidart/laravel-modules

and it keep each module config file in modulesubdir/config folder.
your package detect env function in these config files as a laravel bad practice so report them like this:

|****************************************************************************************************|
|                                                                                                    |
| 53 env() function found:                                                                           |
|  env                                                                                               |
at Modules/Sms/Config/config.php:36                                                                  |
|****************************************************************************************************|

**Comment by hooman-mirghasemi** [comment]
I found out it can ignore in config file

**Comment by imanghafoori1** [comment]
files with `config.php` name are excluded as of version v1.0.200 and above.
No need to mention them in config file.
