### ISSUE TITLE
php artisan check:imports problem

### ISSUE THREAD

**Issue by hooman-mirghasemi** [imanghafoori1/laravel-microscope#169]
when use php artisan check:imports
and code like this:

`use aa/aa/a as b;
class myclass extend b {
...
}
`

this command say wrong import on line 2

**Comment by imanghafoori1** [comment]
Generally, the package works fine with such a situation as below image.
Please provide more details.

![image](https://user-images.githubusercontent.com/6961695/147878458-56bb99ec-c1c2-48f0-a98a-916faff30172.png)

**Comment by hooman-mirghasemi** [comment]
terminal  error:

docker-compose exec laravel php artisan check:imports
Checking imports...

1 errors found for imports
|                                                                            |
|  1 Class does not exist:                                                   |
|  Modules\Financial\Providers\ShetabitPaymentServiceProvider                |
at Modules/Financial/Providers/PaymentServiceProvider.php:8                  |
|****************************************************************************|
 - 565 class references were checked within: 324 classes and 60 blade files
time: 0.506 (sec)



my code:
`<?php

namespace Modules\Financial\Providers;

use Shetabit\Multipay\Payment;
use \Shetabit\Payment\Provider\PaymentServiceProvider as ShetabitPaymentServiceProvider;

class PaymentServiceProvider extends ShetabitPaymentServiceProvider
{
}
`

**Comment by hooman-mirghasemi** [comment]
i remove first  \ from : 
use \Shetabit\Payment\Provider\PaymentServiceProvider as ShetabitPaymentServiceProvider;
to : 
use Shetabit\Payment\Provider\PaymentServiceProvider as ShetabitPaymentServiceProvider;

and now it is correct. but i dont have any run time error with my \ mistake!


Thank you. for your grate package!

**Comment by imanghafoori1** [comment]
your problem is something else, the package works fine with these imports as well:


![image](https://user-images.githubusercontent.com/6961695/147883471-51fd4137-11fb-42e2-9a11-95f9cb41e517.png)

**Comment by imanghafoori1** [comment]
This issue is now fixed.
