### ISSUE TITLE
check imports not working

### ISSUE THREAD

**Issue by HAstaShakiba** [imanghafoori1/laravel-microscope#174]
❯ php artisan check:imports
Checking imports...

In Finder.php line 548:
                                                                        
  The "/app/vendor/laravel/framework/tests/" directory does not exist.

**Comment by imanghafoori1** [comment]
please mention your exact version of laravel, microscope, and OS

`composer show imanghafoori/laravel-microscope` may help

**Comment by HAstaShakiba** [comment]
OS: linux arch manjaro
laravel 5.5
laravel-microscope: v1.0.209

**Comment by imanghafoori1** [comment]
if your project is not something secret, you can put it on a github repo so that I can test it and fix the situation.

**Comment by imanghafoori1** [comment]
please try out the latest version.
