### ISSUE TITLE
controller

### ISSUE THREAD

**Issue by HPWebdeveloper** [imanghafoori1/laravel-microscope#177]
Hello,

Suppose we have a controller (PostController) in App\Http\Controller namespace

class PostController extends Controller

When we move this controller to somewhere else, because of "extends Controller" we have to manually add this line:

use App\Http\Controllers\Controller;

Can microscope resolve this issue?

**Comment by imanghafoori1** [comment]
This is not an issue.

**Comment by HPWebdeveloper** [comment]
Please make a menu for discussions. So we can put such requests/ideas there:

https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions-in-your-repository

you can also make some categories inside the discussions, like: General, Q&A, Ideas ...

Thanks
