### ISSUE TITLE
 Call to undefined method 

### ISSUE THREAD

**Issue by hooman-mirghasemi** [imanghafoori1/laravel-microscope#186]
In last version v1.0.231 after run check:all 

my console:

sail art check:all

Started checking PSR-4 namespaces...
 - 95 namespaces were checked.
Checking imports...

   Error 

  Call to undefined method Imanghafoori\LaravelMicroscope\CheckClassReferencesAreValid::requestIssue()

  at vendor/imanghafoori/laravel-microscope/src/CheckClassReferencesAreValid.php:256
    252▕             [$classReferences, $hostNamespace] = ParseUseStatement::findClassReferences($tokens);
    253▕ 
    254▕             return [$classReferences, $hostNamespace];
    255▕         } catch (\ErrorException $e) {
  ➜ 256▕             self::requestIssue($absFilePath);
    257▕ 
    258▕             return [[], ''];
    259▕         }
    260▕     }

      +29 vendor frames 
  30  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by imanghafoori1** [comment]
please dd the $absFilePath variable on line 256 and send me the content of the file.
thanks.

**Comment by hooman-mirghasemi** [comment]
`
<?php
namespace Modules\Advertisement\Enums;

enum AdStatus: string
{
    case New = 'new';
    case UnderReview = 'under review';
    case Publish = 'publish';
    case Rejected = 'rejected';
    case FinishPublishTime = 'finish publish time';
    case Traded = 'traded';

    public static function getOptions(): array
    {
        return [
            self::New->value => 'جدید',
            self::UnderReview->value => 'در حال بررسی',
            self::Publish->value => 'منتشر شده',
            self::Rejected->value => 'عدم تایید',
            self::FinishPublishTime->value => 'زمان انتشار تمام شده',
            self::Traded->value => 'معامله شده',
        ];
    }
}

`
