### ISSUE TITLE
reports error for controller class in route file

### ISSUE THREAD

**Issue by HPWebdeveloper** [imanghafoori1/laravel-microscope#204]
suppose we have a module and registered that module route file "module_web.php" in its ModuleAserviceprovider considering:

'namespace' => 'ModuleA\Http\Controllers',

I mean we mention this 'namespace' in its serviceprovider and not in the route file.

and in the route file "module_web.php" we have this:

Route::get('/users', 'UsersController');

php artisan check:all does not report any error. Since it is correct.

But if we use this format:

Route::get('/users', UsersController::class);

php artisan check:all **reports** "Class does not exist:  UsersController" while laravel boots well!

**Comment by imanghafoori1** [comment]
You should not use that format for a non-existent class. The thing microscope reports is right. That class does not really exist.
