### ISSUE TITLE
Uninitialized string offset 1 when checking imports

### ISSUE THREAD

**Issue by buzkall** [imanghafoori1/laravel-microscope#209]
I'm using the latest version right now (1.0.242) and throws the following error when checking imports

Checking imports...

     ErrorException 
  
    Uninitialized string offset 1
  
    at vendor/imanghafoori/php-token-analyzer/src/ClassReferenceFinder.php:254
      250▕     }
      251▕ 
      252▕     public static function isBuiltinType($token)
      253▕     {
    ➜ 254▕         return \in_array($token[1], [
      255▕             'object',
      256▕             'string',
      257▕             'never',
      258▕             'private',
  
        +20 vendor frames 
    21  artisan:37
        Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by imanghafoori1** [comment]
please update:
```composer update imanghafoori/laravel-microscope -W```
and see if it is still an issue.

**Comment by buzkall** [comment]
now it works! Thanks!
