### ISSUE TITLE
view:check is broken

### ISSUE THREAD

**Issue by Tlapi** [imanghafoori1/laravel-microscope#217]
Too few arguments to function Imanghafoori\LaravelMicroscope\BladeFiles::check(), 1 passed in /Users/tlapi/Code/ecomailapp/vendor/imanghafoori/laravel-microscope/src/Commands/CheckViews.php on line 103 and exactly 3 expected

**Comment by imanghafoori1** [comment]
Thanks for the report, it is fixed.
