### ISSUE TITLE
php artisan check:psr4

### ISSUE THREAD

**Issue by HPWebdeveloper** [imanghafoori1/laravel-microscope#229]
I moved a model to a module. and then run psr4
![Screen Shot 2022-07-17 at 10 30 51](https://user-images.githubusercontent.com/16323354/179400813-7b8b678d-facb-491b-a7fb-aad973aa4e97.png)

This error seems strange to me! it talks about colors! Is it in Microscope or the code itself? php 7.4, Laravel 6

--
And it happens for the other classes as well. Unfortunately, I cannot use Microscope in this project and am doing manual everything :(

**Comment by imanghafoori1** [comment]
Please mention the exact version of "laravel" and "php" you are using.

**Comment by imanghafoori1** [comment]
Please install the latest version and see what happens.

**Comment by imanghafoori1** [comment]
please use `composer show imanghafoori/laravel-microscope` to see which version you have installed.
