### ISSUE TITLE
Web routes false positive

### ISSUE THREAD

**Issue by robov** [imanghafoori1/laravel-microscope#230]
this generates a class not exists
![image](https://user-images.githubusercontent.com/8173436/179528722-2124a168-56ee-4690-a2e8-9d594dbd755f.png)
![image](https://user-images.githubusercontent.com/8173436/179528942-595f585a-2058-43f2-a041-17ebdb73fd86.png)

When commenting out other code
![image](https://user-images.githubusercontent.com/8173436/179529114-2f23027f-17cb-4f70-ac82-b3181c6fae23.png)
results in no errors

**Comment by imanghafoori1** [comment]
if you do not want to import the full namespace, you should not use the ::class syntax.
It is not really a bug since the `WebhookController::class` does not exist and it has a namespace.

You better pass it as a string: 'WebhookController'

**Comment by robov** [comment]
in this case the namespace is in the use statement :
```use App\Core\Billing\DebtCollection\Controllers\WebhookController;```
and
this Name::class is the laravel perferred way over a stringy version of 'class'

So I do not completely understand what is wrong in my case

**Comment by imanghafoori1** [comment]
could you please upload a summary of the route file?
Since the screen shots do not include the use statements at the top.

**Comment by robov** [comment]
sure
![image](https://user-images.githubusercontent.com/8173436/181512319-d5e42c09-63ab-4fe8-a011-fe80aa45fa84.png)

![image](https://user-images.githubusercontent.com/8173436/181512398-42d652df-2e06-44f2-96e3-8e3c6e13afd6.png)

**Comment by imanghafoori1** [comment]
Not able to reproduce it.
