### ISSUE TITLE
Artisan commands no working

### ISSUE THREAD

**Issue by MirzaazriM** [imanghafoori1/laravel-microscope#239]
After installing library and publishing config file, i tried all of the artisan commands, but none of them seems to work. It seems like command can not be found.
P.S. I didnt have any issues during library installation.
PHP 7.4 / Windows

**Comment by imanghafoori1** [comment]
Your .env file should not be "production".

**Comment by MirzaazriM** [comment]
I found what is the issue. It seems that somebody installed library before and removed it afterwards, but in the meantime config file was published and "is_enabled" was set to false.
Thank you for the answer and this great library.
