### ISSUE TITLE
HTTPNOTFOUNDEXCEPTION after upgrade to latest version

### ISSUE THREAD

**Issue by mariosvasiliou** [imanghafoori1/laravel-microscope#249]
I have run a composer update. I haven't updated the package since 12.01.2022 and when the update finishes the application is not working.
Throws the error HTTPNOTFOUNDEXCEPTION... The route / not found on Laravel 9 and route not found on Laravel 8.
I don't know what changed but breaks the application.
When I remove this package everything works perfectly.
Using PHP 8.0.14 and Laravel 8.37.27
Also tried on PHP 8.0.14 and the latest Laravel 9

**Comment by imanghafoori1** [comment]
Hi
First of all, thanks for taking your time and reporting the issue.
Could you please provide an screen shot of the thrown error?
and also provide the version number that works for you.

**Comment by DarkPain0** [comment]
Hello. You are welcome.
Unfortunately i didn't took any screenshot and I have reverted the packages.
The stack trace did not show anything on your package. Just throwing laravel Http not found exception for a null route. 
To find out which package was causing the problem i constraint the versions to all packages that have upgraded. 
That's how i found out that was this one causing the issue. 
I think when i tried the previous version .281 it was working if i am not mistaken.
But i can check it again tomorrow and let you know.

**Comment by imanghafoori1** [comment]
closing on inactivity/

**Comment by antonio99rus** [comment]
Hi,

Steps to reproduce:
1. Install fresh Laravel 9 project, screenshot:
![screenshot](https://user-images.githubusercontent.com/95843042/218735647-072ae3a3-bc7f-4c71-af29-fe8842dbcfdb.jpg)
2. Run `composer require --dev imanghafoori/laravel-microscope`
3. Just reload the page: ![404 not found on any page](https://user-images.githubusercontent.com/95843042/218736101-e855a12e-bb7a-4bcf-971e-d1e8a9e5831b.jpg)
4. If we publish the error views and insert to `404.blade.php`
```php
@php
dump($exception); 
@endphp
```

and reload the page again, we'll see 
```php
Symfony\Component\HttpKernel\Exception\NotFoundHttpException {#296 ▼ // resources\views/errors/404.blade.php
  #message: "The route / could not be found."
  #code: 0
  #file: "C:\laragon\www\laravel-base\vendor\laravel\framework\src\Illuminate\Routing\AbstractRouteCollection.php"
  #line: 44
  -statusCode: 404
  -headers: []
  trace: {▶}
}
```

P.S. Sorry for my terrible English.
