### ISSUE TITLE
404 on any route after update

### ISSUE THREAD

**Issue by antonio99rus** [imanghafoori1/laravel-microscope#250]
Hi,

Updating v1.0.281 => v1.0.284 introduced routing malfunction.

Problem still exists in 1.0.287 too.

Steps to reproduce:
1. Install fresh Laravel 9 project, screenshot:
![screenshot](https://user-images.githubusercontent.com/95843042/218735647-072ae3a3-bc7f-4c71-af29-fe8842dbcfdb.jpg)
2. Run `composer require --dev imanghafoori/laravel-microscope`
3. Just reload the page: ![404 not found on any page](https://user-images.githubusercontent.com/95843042/218736101-e855a12e-bb7a-4bcf-971e-d1e8a9e5831b.jpg)
4. If we publish the error views and insert to `404.blade.php`
```php
@php
dump($exception); 
@endphp
```

and reload the page again, we'll see 
```php
Symfony\Component\HttpKernel\Exception\NotFoundHttpException {#296 ▼ // resources\views/errors/404.blade.php
  #message: "The route / could not be found."
  #code: 0
  #file: "C:\laragon\www\laravel-base\vendor\laravel\framework\src\Illuminate\Routing\AbstractRouteCollection.php"
  #line: 44
  -statusCode: 404
  -headers: []
  trace: {▶}
}
```

P.S. Sorry for my terrible English.

_Originally posted by @antonio99rus in https://github.com/imanghafoori1/laravel-microscope/issues/249#issuecomment-1429670377_

**Comment by imanghafoori1** [comment]
Could you please try `v1.0.283` and see if it works?
and please tell me your laravel and PHP version.

**Comment by antonio99rus** [comment]
Hi, 

after installing `v1.0.283` on fresh laravel 404 error remains.

Also, from the first screenshot:
```
Laravel v9.51.0 (PHP v8.1.10) 
```

**Comment by antonio99rus** [comment]
More info: (Laravel 9.52.0, PHP v8.1.10):

Fresh install: all routes work ok.
Microscope v1.0.281: all ok.
Microscope any version in v1.0.282 - v1.0.288: 404 on any route.

So, I suppose that something introduced in `v1.0.282` is the source of this bug.

**Comment by imanghafoori1** [comment]
Thanks for the update, I will investigate it today afternoon.

**Comment by imanghafoori1** [comment]
What is your OS? do you run the code on windows?
I think the only suspectable thing is this:

`LaravelMicroscopeServiceProvider.php`
![image](https://user-images.githubusercontent.com/6961695/220217715-edad7fc1-ff52-4679-977b-94a34bebb637.png)

you can comment this out in the service provider to see if it works.

**Comment by antonio99rus** [comment]
Yes, it is!

I work with Laragon on Windows. 

Removing this Windows check solves the problem. 

Why this check was added in `v1.0.282`?

**Comment by imanghafoori1** [comment]
We assume Windows is a local dev server and not a production server.
But it is strange why it causes problem for you.
Thanks I think on it and fixed it today.

**Comment by antonio99rus** [comment]
Definitely, no windows on production.

The problem is that since `v1.0.282` on Windows we don't respect `$this->app->runningInConsole()` and try to start Microscope during a normal application request from the browser, thus breaking Laravel routing.

Thanks, have a nice day.

**Comment by imanghafoori1** [comment]
I think you can now enjoy the `v1.0.290`

**Comment by antonio99rus** [comment]
Big thanks!!!
