### ISSUE TITLE
PHP 8.2 mistakely remove correct namespace

### ISSUE THREAD

**Issue by hmdshariati** [imanghafoori1/laravel-microscope#261]
PHP 8.2
![Screenshot from 2023-03-06 17-05-11](https://user-images.githubusercontent.com/6438294/223125289-2a28853b-90a8-4e3a-aee0-8c1e28ee0ef4.png)
![Screenshot from 2023-03-06 17-05-25](https://user-images.githubusercontent.com/6438294/223125314-fa42148c-9cab-43d8-be3d-00653ff7b1f3.png)
![Screenshot from 2023-03-06 17-05-39](https://user-images.githubusercontent.com/6438294/223125915-f9959da1-de03-457f-a188-e88fc48ae408.png)
why?

**Comment by imanghafoori1** [comment]
Please also mention your:
OS (win/linux/mac)
laravel version 
microscope version

You may run `composer show imanghafoori/laravel-microscope` to see the version.

**Comment by imanghafoori1** [comment]
closing on inactivity.

**Comment by hmdshariati** [comment]
laravel 10
on docker (alpine php8.2)
last version of microscope ( a few days ago)

it's on my office. my co-worker use pint and phpstan. what's differences vs your package?

**Comment by imanghafoori1** [comment]
Please also paste the autoload psr-4 of your composer.json file.

You can use composer show imanghafoori/laravel-microscope to see the
version.

**Comment by hmdshariati** [comment]
![image](https://user-images.githubusercontent.com/6438294/224543786-9f8477f8-c1d1-48e3-bf9d-f204637b376a.png)

**Comment by imanghafoori1** [comment]
Please also paste the autoload psr-4 of your composer.json file.

**Comment by hmdshariati** [comment]
![Screenshot from 2023-03-12 18-33-382](https://user-images.githubusercontent.com/6438294/224553455-11701bd3-5d20-4755-abae-241db8e3afdd.png)
@imanghafoori1

**Comment by imanghafoori1** [comment]
it seems that it is the 11th error message, Were all the other first 10 messages correct?

**Comment by imanghafoori1** [comment]
please try the latest version and tell me if the problem is still there.
