### ISSUE TITLE
False negative on Enums

### ISSUE THREAD

**Issue by yormy** [imanghafoori1/laravel-microscope#267]
The following code triggers the check:import 
```
            if ($value instanceof \Enum) {
                $value = $value->value;
            }
```
![image](https://github.com/imanghafoori1/laravel-microscope/assets/37929978/3c1d4686-32f1-464f-b757-27ea6a01fcf8)

But it should be correct

**Comment by imanghafoori1** [comment]
Thanks for the report.
I will fix it soon.

**Comment by imanghafoori1** [comment]
you can have the fix in the latest patch version as of now.
