### ISSUE TITLE
LogicException Error

### ISSUE THREAD

**Issue by abbasmashaddy72** [imanghafoori1/laravel-microscope#282]
On Almost Every Command, I get this below Error Message

Using All Latest Version
`"imanghafoori/laravel-microscope": "^1.0",`
`"laravel/framework": "^10.10",`

I have Not Published config Files

```
 LogicException 

  You must call one of in() or append() methods before iterating over a Finder.

  at vendor/symfony/finder/Finder.php:670
    666▕      */
    667▕     public function getIterator(): \Iterator
    668▕     {
    669▕         if (0 === \count($this->dirs) && 0 === \count($this->iterators)) {
  ➜ 670▕             throw new \LogicException('You must call one of in() or append() methods before iterating over a Finder.');
    671▕         }
    672▕ 
    673▕         if (1 === \count($this->dirs) && 0 === \count($this->iterators)) {
    674▕             $iterator = $this->searchInDirectory($this->dirs[0]);

      +15 vendor frames 

  16  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by abbasmashaddy72** [comment]
> On Almost Every Command, I get this below Error Message
> 
> Using All Latest Version `"imanghafoori/laravel-microscope": "^1.0",` `"laravel/framework": "^10.10",`
> 
> I have Not Published config Files
> 
> ```
>  LogicException 
> 
>   You must call one of in() or append() methods before iterating over a Finder.
> 
>   at vendor/symfony/finder/Finder.php:670
>     666▕      */
>     667▕     public function getIterator(): \Iterator
>     668▕     {
>     669▕         if (0 === \count($this->dirs) && 0 === \count($this->iterators)) {
>   ➜ 670▕             throw new \LogicException('You must call one of in() or append() methods before iterating over a Finder.');
>     671▕         }
>     672▕ 
>     673▕         if (1 === \count($this->dirs) && 0 === \count($this->iterators)) {
>     674▕             $iterator = $this->searchInDirectory($this->dirs[0]);
> 
>       +15 vendor frames 
> 
>   16  artisan:35
>       Illuminate\Foundation\Console\Kernel::handle()
> ```

I tried Publishing Config and ignoring the folder but still same:


```
'ignore' => [
        'vendor*'
    ],
```

**Comment by imanghafoori1** [comment]
Thanks for the report. 
could you please try v1.0.330 real quick?

**Comment by abbasmashaddy72** [comment]
> Thanks for the report. could you please try v1.0.330 real quick?

Sorry for the Late Response, I tried but shows:


```
composer require "imanghafoori/laravel-microscope@^1.0.330" --dev

In PackageDiscoveryTrait.php line 376:
                                                                                    
  Could not find a matching version of package imanghafoori/laravel-microscope@^1.  
  0.330. Check the package spelling, your version constraint and that the package   
  is available in a stability which matches your minimum-stability (dev).
```
