### ISSUE TITLE
Incorrectly reports class does not exist for named arguments

### ISSUE THREAD

**Issue by PatrickSJ** [imanghafoori1/laravel-microscope#288]
If a named argument is used as follows:

```php
namespace App\Dto;

$test = new SomeClass(date_created: Carbon::parse($some_value));
``` 

then the error `Class does not exist App\Dto\date_createdCarbon` is reported when checking imports & class references.

Also similar to above I could get a error with `$test = new SomeClass(date_created: Cast::from((string) $some_value))`  which would state `Class does not exist App\Dto\(string)`

This is on PHP 8.1.

**Comment by imanghafoori1** [comment]
@alikhosravidev

**Comment by imanghafoori1** [comment]
Sorry, I can not reproduce this problem. Maybe you are using an outdated version of microscope.
make sure you are using the lastest version by running:

```bash
composer update imanghafoori/laravel-microscope -W
```
