### ISSUE TITLE
Make package composer global as a CLI

### ISSUE THREAD

**Issue by innoflash** [imanghafoori1/laravel-microscope#29]
Hi to @imanghafoori1 and contributors. DO you think you can make this package a CLI app to install on the system rather than on every project? 

If you were to ask me i would recommend Laravel Zero for building this and if you think its a good idea i am willing to help wherever i can.

Cheers

**Comment by imanghafoori1** [comment]
Well, not at this stage of development, for now we are focusing on bugs, features, code refactors.
to make it stable.
After that if all the features were compatible with all the version of laravel. 
YES. It is a good idea.
For now there are still a lot of bugs to discover and fix.
