### ISSUE TITLE
Logging early

### ISSUE THREAD

**Issue by innoflash** [imanghafoori1/laravel-microscope#40]
https://github.com/imanghafoori1/laravel-microscope/blob/a870f68974bda5bfe01b1c7760ecb7b2ddc1629d/src/Checks/CheckViewFilesExistence.php#L46-L50

I think this function rather have to feed errors to the ErrorPrinter rather than printing here prematurely

**Comment by imanghafoori1** [comment]
Create a PR for it.  :D
It would be welcome

**Comment by innoflash** [comment]
ok cool
