### ISSUE TITLE
artisan check:all, It doesn't look very nice on the display

### ISSUE THREAD

**Issue by wilbur-oo** [imanghafoori1/laravel-microscope#42]
![image](https://user-images.githubusercontent.com/7148309/79105320-02e62580-7da3-11ea-9d63-459a894ffc85.png)

**Comment by imanghafoori1** [comment]
The file address is intentionally out of the table, si that phpstorm will identify it as a clickable link. 

Anyway you are right,  it ks not still very pretty. 
If you can make it better please make a pull request. It would be welcome.

**Comment by innoflash** [comment]
I think to fix that one you need to add end of line when the command being run is check:all. 

Let me make a quick PR

**Comment by imanghafoori1** [comment]
This is somewhat fixed now by the #46
