### ISSUE TITLE
bug in "php artisan check:imports"

### ISSUE THREAD

**Issue by meysamzandy** [imanghafoori1/laravel-microscope#50]
I'm using your great package and when I used :
 `php artisan check:imports`
gave an error:
`1 Class does not exist: 
App\Http\Controllers\request   <==== does not exist
at app\Http\Controllers\CallBack.php:23   `
while I using : 
`Illuminate\Http\Request;`

in my project
` public function mellatBank(request $request): void {}`

**Comment by imanghafoori1** [comment]
Request not request

Capital R is correct.

**Comment by meysamzandy** [comment]
eyvay, that's my fault.
