### ISSUE TITLE
conflict overriden routes

### ISSUE THREAD

**Issue by babakmoeinifar** [imanghafoori1/laravel-microscope#53]
I have one route in web.php -> products.index         (/products)
and another one in api.php  -> products.index too   (api/client/products)
but they are different in url

| 28 Route with uri: GET,HEAD: /products is overridden.                                                 |
|  Route name: products.index is overridden by an other route with same uri.

**Comment by imanghafoori1** [comment]
It seems they both have the same name.

**Comment by imanghafoori1** [comment]
I think your route your route is overridden some where else
