### ISSUE TITLE
Exit status code

### ISSUE THREAD

**Issue by gitetsu** [imanghafoori1/laravel-microscope#59]
I would like to run these commands in CI service.
So, how about exit non-zero status code when check failed?

**Comment by imanghafoori1** [comment]
hhhmmm... 
Honestly, I have no idea about the needs of Ci/Cd process.

But I have tried to de-couple the error logger from the error detector.
They communicate through event/listener mechanism.

So it means you can contribute, a new class or another package which listens to events and reacts according to the needs of CI/CD.

The code is not perfect yet but I am still here, ready to make changes as needed.

Happy if I can help you with that.
Subasa Ozara. ;)

**Comment by amir9480** [comment]
@gitetsu 
I gonna dive into this today to fix it.

**Comment by imanghafoori1** [comment]
Hey man, could you please carefully check for this issue in the latest release?
I merged and then modified the PR.

Remember some commands do not make sense as CI/CD processes and they are just there in order to help us refactor the code.

**Comment by gitetsu** [comment]
I've tested some commands like `check:best_practice` or `check:dd` and worked fine.

@imanghafoori1 @amir9480 
Thank you very much for the quick fix!
