### ISSUE TITLE
Strange memory size issue

### ISSUE THREAD

**Issue by Algeneralo** [imanghafoori1/laravel-microscope#65]
As I was trying to install this package, I got an error about memory size issue.
I don't understand why this package needs more than 1.5G of memory?

![image](https://user-images.githubusercontent.com/32073999/83564209-fff6ee00-a524-11ea-8e41-5b8b841ba4b1.png)

**Comment by imanghafoori1** [comment]
This is not related to this particular package,  rather to composer. 
Take a look at the closed issues. 

You have to increase your php memory limit, to 2gigs. 
From php.ini
