### ISSUE TITLE
stringy_classes Error

### ISSUE THREAD

**Issue by lsfiege** [imanghafoori1/laravel-microscope#66]
Hi! Thank you for this amazing component!

I have an error when I run the `php artisan check:stringy_classes` command: It throws the following error output:
```
Checking strings...
PHP Fatal error:  Cannot declare class App\Task, because the name is already in use in /home/luckas/Code/mol/interno/app/Task.php on line 9

   Symfony\Component\ErrorHandler\Error\FatalError 

  Cannot declare class App\Task, because the name is already in use

  at app/Task.php:9
     5| use Illuminate\Database\Eloquent\Model;
     6| use Illuminate\Database\Eloquent\SoftDeletes;
     7| use Illuminate\Support\Carbon;
     8| 
  >  9| class Task extends Model
    10| {
    11|     use SoftDeletes;
    12| 
    13|     protected $dates = [


   Whoops\Exception\ErrorException 

  Cannot declare class App\Task, because the name is already in use

  at app/Task.php:9
     5| use Illuminate\Database\Eloquent\Model;
     6| use Illuminate\Database\Eloquent\SoftDeletes;
     7| use Illuminate\Support\Carbon;
     8| 
  >  9| class Task extends Model
    10| {
    11|     use SoftDeletes;
    12| 
    13|     protected $dates = [

      +1 vendor frames 
  2   [internal]:0
      Whoops\Run::handleShutdown()
```

I have only one `App\Task` class model, Is this a false positive or is it another error?

**Comment by imanghafoori1** [comment]
Hhhhmmm,  check that trait are correctly referrenced. 
Run
Check:import
Check:psr4

First to see what happens.

**Comment by imanghafoori1** [comment]
I think there is some problem with 
SoftDeletes; trait.

**Comment by lsfiege** [comment]
The psr4 and import checks are ok

**Comment by imanghafoori1** [comment]
I investigate the issue, thanks for report.

**Comment by lsfiege** [comment]
I've ran the command with an empty Task class and it still failing, maybe this is a problem from the legacy codebase I'm working on. So I'm going to close this issue. Thank you for your support!

**Comment by imanghafoori1** [comment]
Let this be open until we find the root cause of this confusion.

**Comment by pierrepavlov** [comment]
Did you ever find out what was causing this issue? I'm just trying the package and I get this exact error. It's a legacy code base which has been upgraded to Laravel 8, so unsure if there's something missing/wrong further back.
