### ISSUE TITLE
Doesn't work with Laravel 5.4.36 (which is no problem)

### ISSUE THREAD

**Issue by HenkPoley** [imanghafoori1/laravel-microscope#67]
..but you might want to specify a minimum of 5.5 in your composer.json

After putting `\Imanghafoori\LaravelMicroscope\LaravelMicroscopeServiceProvider::class,` in `config/app.php` , this results in:

```
$ php artisan check

In SpyRouteCollection.php line 14:
                                                                  
  Call to undefined method Illuminate\Routing\Route::getDomain()  
```

---

5.4, no `getDomain()`: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Routing/Route.php
5.5, `getDomain()`: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Routing/Route.php#L568

**Comment by imanghafoori1** [comment]
Thanks for the report.
Could you please install the dev-master version to see if it works?
I made some changes

**Comment by HenkPoley** [comment]
Thanks for fixing it for old Laravel 5.4 👍

Now some individual checks break because there's brokenness in the codebase I'm working with. But that's not your problem.

**Comment by imanghafoori1** [comment]
@HenkPoley 
I think it may be still my problem,  or I can deal with those situations. 

Providing information for those would also be welcome.

**Comment by HenkPoley** [comment]
It is things like redefining a variable that was also defined in a trait (e.g. $attributes in a class that uses \Illuminate\Database\Eloquent\Concerns\HasAttributes). Which the PHP interpreter will just shrug about for now, but I understand why you shouldn't confuse ownership ("👋 rust").

Also I had some mismatching returns after having them filled in by vimeo/psalm on just some interfaces. IMHO psalm should block 'fixing' return types if there are un-fixed consumers of that interface. But not your problem.

**Comment by HenkPoley** [comment]
Maybe there is one thing, `php artisan check:imports`

```
| 29 Class does not exist:                                                                              |
|  'regex:/[ \!"\#\$\%\&\'\(\)\*\+\,\-\.\/\:\;<\=\>\?\@\[\]\^\_\`\{\|\}\~\\\]/'   <==== does not exist |
```

That doesn't look like an import to me 🤷‍♂️

**Comment by imanghafoori1** [comment]
It is because it contains both back-slash and @ so it is considered to be a class@method syntax. 

But how we can identify regexes like this?

**Comment by imanghafoori1** [comment]
I think the latest version of `dev-master `should not report the regex as an error.

**Comment by HenkPoley** [comment]
It seems to only list 'legitimate' errors.

Maybe technically, since we are talking about Laravel, a line like `Log::error($e->getMessage());` is not problematic. It does not refer to ClassPath\Log, Laravel will substitute in Log with it's own Log class from `config/app.php` `'aliases'`.

**Comment by imanghafoori1** [comment]
Class aliases which laravel provides for shorter syntax can be detected to be valid.
Since we first boot up laravel and then use `class_exists()`, something like:
`\Log::info` should be detected to be valid by `class_exists()`

**Comment by HenkPoley** [comment]
I'd swear that `Log` without the backslash works as well. Though personally I always write the full import.

**Comment by imanghafoori1** [comment]
Currently, the microscope should be smart enough to detect a real working alias from a mistyped class which does not work. (unlike IDEs which can not.)

If you see irrelevant errors you can open up an issue for it.
