### ISSUE TITLE
Error when using arrow functions

### ISSUE THREAD

**Issue by samuelhgf** [imanghafoori1/laravel-microscope#68]
Hi,

I am receiving this error when the scan pass through an arrow function:

It says that the error in on line 105

`syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ',' or ')'`

My code:

`104|         }else{
  > 105|             $tagsCollection = $tags->map(fn($tag) => tagResolver($tag->tag));
    106| 
    107|             $valuesCollection = $tags->map(fn($tag) => $tag->pivot->value);
    108|         }`

**Comment by imanghafoori1** [comment]
Hi,
It is kind strange,  I will check that. 
Thanks for reporting.

**Comment by imanghafoori1** [comment]
I guess your cli version of php is below v7.4
Please run `php --version` command to double-check it.

**Comment by samuelhgf** [comment]
My cli was below 7.4
