### ISSUE TITLE
php artisan check:blade_queries

### ISSUE THREAD

**Issue by vishalinfyom** [imanghafoori1/laravel-microscope#69]
I have some constants on my models.

e.g

const STATUS = 1;

and i'm using it into blade files 

`App\Models\{ModelName}::STATUS`

while running query command for blade files its showing this line as query

**Comment by imanghafoori1** [comment]
Yeah,  it should also check that a mothod is being called,  but using a constant in this way in blade files is still a bad practice. 

Blade files should not know about class names and their namespaces.

**Comment by imanghafoori1** [comment]
This is not a major issue, and I do not find a good way to avoid it.
Anyway, I think using eloquent constants is as bad as performing queries. So the detection is somewhat correct.
