### ISSUE TITLE
  Undefined index: file 

### ISSUE THREAD

**Issue by vandadsoft** [imanghafoori1/laravel-microscope#70]
Undefined index: file

  at A:\www\laravel\vendor\imanghafoori\laravel-microscope\src\ErrorReporters\ErrorPrinter.php:116
```
    112|             $routeUri = $this->yellow($routeUri);
    113|             $msg = 'Route uri: '.$routeUri;
    114|         }
    115| 
  > 116|         $msg .= "\n".' at '. $info[0]['file'].':'.$info[0]['line'];
    117|         $msg .= "\n".' is overridden by ';
    118| 
    119|         $routeName = $route2->getName();
    120|         if ($routeName) {

```
  1   A:\www\laravel\vendor\imanghafoori\laravel-microscope\src\ErrorReporters\ErrorPrinter.php:116
      PragmaRX\Tracker\Support\Exceptions\Handler::handleError("Undefined index: file", "A:\www\shago\vendor\imanghafoori\laravel-microscope\src\ErrorReporters\ErrorPrinter.php")

  2   A:\www\laravel\vendor\imanghafoori\laravel-microscope\src\ErrorReporters\ConsolePrinterInstaller.php:74
      Imanghafoori\LaravelMicroscope\ErrorReporters\ErrorPrinter::routeDefinitionConflict(Object(Illuminate\Routing\Route), Object(Illuminate\Routing\Route))

**Comment by imanghafoori1** [comment]
upgrade to version v1.0.102 and it should be ok
