### ISSUE TITLE
php artisan check:import gives error when alias is used

### ISSUE THREAD

**Issue by vishalinfyom** [imanghafoori1/laravel-microscope#72]
i have added following alias in `config/app.php`

```
  'DataTables'   => Yajra\DataTables\Facades\DataTables::class,

```

now while running imports command its returning controllers where that alias is used, i think that should not be happen

Thanks

**Comment by imanghafoori1** [comment]
Make sure about the upperCase lowercase stuff, to be consistent. 
and also check to see if the package is not in the require-dev.

**Comment by imanghafoori1** [comment]
If think it should be `Datatable`  with no `s` at the end
