### ISSUE TITLE
Route::group(...) is not correct

### ISSUE THREAD

**Issue by moskoweb** [imanghafoori1/laravel-microscope#77]
When executing the command to check the views it returns the following error:

`['namespace' => 'Barryvdh\Debugbar\Controllers'] passed to Route::group(...) is not correct.`

However, I could not understand how to correct this error.

**Comment by imanghafoori1** [comment]
As of the latest version, you can ignore paths from the config file, so that these redundant errors would be suppressed.

**Comment by moskoweb** [comment]
Hello @imanghafoori1, I had solved the problem, but now he returned:

```['namespace' => 'Arrilot\Widgets\Controllers'] passed to Route::group(...) is not correct.```

**Comment by imanghafoori1** [comment]
Thanks for the report, but keep in mind that you can also ignore specific namespaces in new versions

**Comment by imanghafoori1** [comment]
Could you please go to `SpyRouter` file line 57:
and change it to:

```
if ($ns && isset($attributes['namespace']) && \str_replace(['\\', '/'], DIRECTORY_SEPARATOR, $ns) !== $dir && ! is_dir($dir)) {```

to see if it solves the problem or not?
