### ISSUE TITLE
PHP Fatal Error in SpyDispatcher::listen($events, $listener) using Laravel 8.4.0

### ISSUE THREAD

**Issue by sean-leopenaws** [imanghafoori1/laravel-microscope#81]
On Composer install of the package on Laravel 8.4.0, composer is returning with the following fatal error:

PHP Fatal error:  Declaration of Imanghafoori\LaravelMicroscope\SpyClasses\SpyDispatcher::listen($events, $listener) 
must be compatible with Illuminate\Events\Dispatcher::listen($events, $listener = NULL)

It seems Laravel is expecting a null default for the $listener.

![image](https://user-images.githubusercontent.com/49963596/93527737-68ab8e80-f98d-11ea-95b7-c55a7d17e993.png)

**Comment by imanghafoori1** [comment]
it should be ok as of version v1.0.124
good lock.
