### ISSUE TITLE
Undefined index: file

### ISSUE THREAD

**Issue by parsa212** [imanghafoori1/laravel-microscope#82]
I got this error after running `php artisan check:routes` command.
 Undefined index: file
 at C:\xamppN\htdocs\ticket\ticket\vendor\imanghafoori\laravel-microscope\src\ErrorReporters\ErrorPrinter.php:116

112|     }
    113| 
    114|     public function routeDefinitionConflict($route1, $route2, $info)
    115|     {
  > 116|         if (LaravelPaths::isIgnored($info[0]['file'])) {
    117|             return;
    118|         }
    119| 
    120|         $key = 'routeDefinitionConflict';

1   C:\xamppN\htdocs\ticket\ticket\vendor\imanghafoori\laravel-microscope\src\ErrorReporters\ErrorPrinter.php:116
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: file", "C:\xamppN\htdocs\ticket\ticket\vendor\imanghafoori\laravel-microscope
\src\ErrorReporters\ErrorPrinter.php", [Object(Illuminate\Routing\Route), Object(Illuminate\Routing\Route)])

  2   C:\xamppN\htdocs\ticket\ticket\vendor\imanghafoori\laravel-microscope\src\ErrorReporters\ConsolePrinterInstaller.php:74
      Imanghafoori\LaravelMicroscope\ErrorReporters\ErrorPrinter::routeDefinitionConflict(Object(Illuminate\Routing\Route), Object(Illuminate\Routing\Route))

**Comment by imanghafoori1** [comment]
try v1.0.125
