### ISSUE TITLE
Passport routes

### ISSUE THREAD

**Issue by cdebattista** [imanghafoori1/laravel-microscope#83]
using this

```
Passport::routes(function($route){
    $route->forAccessTokens();
});
```

will show 

`|*******************************************************************************************************|
|                                                                                                       |
|  5 route name 'passport.authorizations.approve' does not exist:                                       |
|  route('passport.authorizations.approve')  <=== is wrong                                              |
at vendor\laravel\passport\src/../resources/views\authorize.blade.php:67                                |
|                                                                                                       |
|*******************************************************************************************************|
|                                                                                                       |
|  6 route name 'passport.authorizations.deny' does not exist:                                          |
|  route('passport.authorizations.deny')  <=== is wrong                                                 |
at vendor\laravel\passport\src/../resources/views\authorize.blade.php:77                                |
|                                                                                                       |
|*******************************************************************************************************|
`

**Comment by imanghafoori1** [comment]
You can add these to ignored paths in the config file.
