### ISSUE TITLE
[Laravel 8] - seeds => seeders

### ISSUE THREAD

**Issue by cdebattista** [imanghafoori1/laravel-microscope#84]
https://github.com/imanghafoori1/laravel-microscope/blob/ba332ba5977c756e87bc24aa2b58053d0afbcd50/src/Commands/CheckImports.php#L37
```json
"autoload": {
    "psr-4": {
        "App\\": "app/",
        "Database\\Factories\\": "database/factories/",
        "Database\\Seeders\\": "database/seeders/"
    }
},
```

**Comment by imanghafoori1** [comment]
Please provide more information, is it throwing error?

**Comment by cdebattista** [comment]
This is because of this
vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeederMakeCommand.php

```php
protected function getPath($name)
    {
        if (is_dir($this->laravel->databasePath().'/seeds')) {
            return $this->laravel->databasePath().'/seeds/'.$name.'.php';
        } else {
            return $this->laravel->databasePath().'/seeders/'.$name.'.php';
        }
    }
```



C:\Users\De Battista\Dropbox (Residence mixte)\99 - WWW Applications\crm>php artisan check:imports
Checking imports...

   Symfony\Component\Finder\Exception\DirectoryNotFoundException 

  The "C:\Users\De Battista\Dropbox (Residence mixte)\99 - WWW Applications\crm\database\seeds" directory does not exist.

  at C:\Users\De Battista\Dropbox (Residence mixte)\99 - WWW Applications\crm\vendor\symfony\finder\Finder.php:589
    585▕             } elseif ($glob = glob($dir, (\defined('GLOB_BRACE') ? GLOB_BRACE : 0) | GLOB_ONLYDIR | GLOB_NOSORT)) {
    586▕                 sort($glob);
    587▕                 $resolvedDirs = array_merge($resolvedDirs, array_map([$this, 'normalizeDir'], $glob));
    588▕             } else {
  ➜ 589▕                 throw new DirectoryNotFoundException(sprintf('The "%s" directory does not exist.', $dir));
    590▕             }
    591▕         }
    592▕
    593▕         $this->dirs = array_merge($this->dirs, $resolvedDirs);

  1   C:\Users\De Battista\Dropbox (Residence mixte)\99 - WWW Applications\crm\vendor\imanghafoori\laravel-microscope\src\FileReaders\Paths.php:11
      Symfony\Component\Finder\Finder::in("C:\Users\De Battista\Dropbox (Residence mixte)\99 - WWW Applications\crm\database\seeds")

  2   C:\Users\De Battista\Dropbox (Residence mixte)\99 - WWW Applications\crm\vendor\imanghafoori\laravel-microscope\src\Commands\CheckImports.php:37
      Imanghafoori\LaravelMicroscope\FileReaders\Paths::getAbsFilePaths("C:\Users\De Battista\Dropbox (Residence mixte)\99 - WWW Applications\crm\database\seeds")

**Comment by imanghafoori1** [comment]
try v1.0.126
