### ISSUE TITLE
[Laravel 8] - Factories

### ISSUE THREAD

**Issue by cdebattista** [imanghafoori1/laravel-microscope#85]
not use anymore on 8
 Class 'Illuminate\Database\Eloquent\Factory' not found

**Comment by imanghafoori1** [comment]
what does it mean?

**Comment by imanghafoori1** [comment]
try v1.0.126

**Comment by cdebattista** [comment]
ok weird composer require imanghafoori/laravel-microscope --dev 
installed me the 1.0.125 instead of 126

Works now.

**Comment by imanghafoori1** [comment]
Not weird I fixed it after your report ;) 
Hope you enjoy it
