### ISSUE TITLE
php artisan check:stringy_classes

### ISSUE THREAD

**Issue by cdebattista** [imanghafoori1/laravel-microscope#86]
I have the default Controller here : https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Controller.php
but got errors.

 Cannot declare class App\Http\Controllers\Controller, because the name is already in use

  at C:\Users\De Battista\Dropbox (Residence mixte)\99 - WWW Applications\crm\app\Http\Controllers\Controller.php:10
      6▕ use Illuminate\Routing\Controller as BaseController;
      7▕ use Illuminate\Foundation\Validation\ValidatesRequests;
      8▕ use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
      9▕
  ➜  10▕ class Controller extends BaseController
     11▕ {
     12▕     use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
     13▕ }
     14▕

  1   C:\Users\De Battista\Dropbox (Residence mixte)\99 - WWW Applications\crm\vendor\filp\whoops\src\Whoops\Run.php:408
      Whoops\Run::handleError("Cannot declare class App\Http\Controllers\Controller, because the name is already in use", "C:\Users\De Battista\Dropbox (Residence mixte)\99 - WWW Applications\crm\app\Http\Controllers\Controller.php")

**Comment by imanghafoori1** [comment]
I can not reproduce this on laravel 8 and microscope v1.0.126
