### ISSUE TITLE
no commands defined error

### ISSUE THREAD

**Issue by abbasmashaddy72** [imanghafoori1/laravel-microscope#88]
There are no commands defined in the "check" namespace.

When typed and command with check or pp.
But has installed successfully in vendors folder.
I am using in Laravel 6.x.
@imanghafoori1

**Comment by imanghafoori1** [comment]
Check your env file
Your should not be in production mode for this to work

**Comment by abbasmashaddy72** [comment]
Okay

**Comment by abbasmashaddy72** [comment]
Thanks brother it is working fine.

**Comment by abbasmashaddy72** [comment]
I am getting this error how to fix this

PHP Fatal error:  Cannot redeclare active_menu() (previously declared in C:\xampp\htdocs\test\@core\app\Helpers\helpers.php:10) in C:\xampp\htdocs\test\@core\app\Helpers\helpers.php on line 14

   Symfony\Component\Debug\Exception\FatalErrorException  : Cannot redeclare active_menu() (previously declared in C:\xampp\htdocs\test\@core\app\Helpers\helpers.php:10)

  at C:\xampp\htdocs\test\@core\app\Helpers\helpers.php:14
    10| function active_menu($url)
    11| {
    12|
    13|     return $url == request()->path() ? 'active' : '';
  > 14| }
    15|
    16| function active_menu_frontend($url)
    17| {
    18|


   Whoops\Exception\ErrorException  : Cannot redeclare active_menu() (previously declared in C:\xampp\htdocs\test\@core\app\Helpers\helpers.php:10)

  at C:\xampp\htdocs\test\@core\app\Helpers\helpers.php:14
    10| function active_menu($url)
    11| {
    12|
    13|     return $url == request()->path() ? 'active' : '';
  > 14| }
    15|
    16| function active_menu_frontend($url)
    17| {
    18|

  Exception trace:

  1   Whoops\Run::handleError("Cannot redeclare active_menu() (previously declared in C:\xampp\htdocs\test\@core\app\Helpers\helpers.php:10)", "C:\xampp\htdocs\test\@core\app\Helpers\helpers.php")
      C:\xampp\htdocs\test\@core\vendor\filp\whoops\src\Whoops\Run.php:408

  2   Whoops\Run::handleShutdown()
      [internal]:0

**Comment by imanghafoori1** [comment]
if (!function_exists('xyz')) {
   function xyz (){
       ///....
   }
}
