### ISSUE TITLE
issue with Laravel Nova

### ISSUE THREAD

**Issue by amirkoklan** [imanghafoori1/laravel-microscope#95]
always after the first run of `php artisan check:all` I see this change in my code from Microscope which is absolutely wrong:
![Screenshot 2020-10-26 at 00 26 19](https://user-images.githubusercontent.com/1830343/97121880-e055a180-1721-11eb-98a3-a8051952f925.png)

**Comment by amirkoklan** [comment]
I could solve the first issue but not the second one.

**Comment by imanghafoori1** [comment]
Hi Amir, what is your version of nova, since I have tested it against nova many times, and did not experienced such a thing.

**Comment by imanghafoori1** [comment]
I made some tweaks so that something like 'App\\' would be considered valid.
But I can not reproduce the bug you mentioned above with nova.
Everything is fine for me.

**Comment by amirkoklan** [comment]
v3.10.0

**Comment by imanghafoori1** [comment]
I have nova v3.6 (You may send me the newer version.)
I will add a feature in the next release so that you can blacklist the nova namespace and it would not be scanned by microscope.

**Comment by imanghafoori1** [comment]
You can ignore the nova's namespace in the config file in the latest version. so that microscope does not scan it.

**Comment by amirkoklan** [comment]
This is what I am getting when I install now:

![Screenshot 2020-11-01 at 11 43 16](https://user-images.githubusercontent.com/1830343/97800684-84b27900-1c37-11eb-8378-3c1ec972b412.png)

**Comment by imanghafoori1** [comment]
Sorry for that try v1.0.135
I will check new version of nova tomorrow to see what exactly is happening there.

**Comment by imanghafoori1** [comment]
I tested this on nova 3.14.0 but there was no problem.
Anyway I recommend you to have this config so that nova files won't be scanned.
```php
return [
    /**
     * An array of patterns that should be ignored for the checks.
     */
    'ignore' => [],

    /**
     * You can turn off the extra variable passing detection, which performs some logs.
     */
    'log_unused_view_vars' => true,

    /**
     * An array of root namespaces to be ignored while scanning for errors.
     */
    'ignored_namespaces' => [
        'Laravel\\Nova\\', 
        'Laravel\\Nova\\Tests\\'
    ],
];
```
