### ISSUE TITLE
 php artisan check:psr4 Not Work on classes with Dockblock

### ISSUE THREAD

**Issue by hossein7441** [imanghafoori1/laravel-microscope#98]
this command not work when my model classes have dockblock, please check it

**Comment by imanghafoori1** [comment]
Please provide a clean example and the error you got

**Comment by hossein7441** [comment]
`namespace App\Models;

use Closure;
use Illuminate\Support\Facades\Auth;

/**
 * App\Models\Company
 *
 * @property int $id
 * @property int $user_id
 * @property string $name
 * @property string|null $tel
 * @property string|null $about
 * @property string|null $logo
 * @property string|null $address
 * @property int $currency_id
 * @property int $is_active
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\CompanyEmployee[] $employees
 * @property-read int|null $employees_count
 * @property-read mixed $logo_url
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\ISMSPeriod[] $ismsPeriods
 * @property-read int|null $isms_periods_count
 * @property-read \App\Models\User $user
 * @method static \Illuminate\Database\Eloquent\Builder|Company newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Company newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Company query()
 * @method static \Illuminate\Database\Eloquent\Builder|Company whereAbout($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Company whereAddress($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Company whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Company whereCurrencyId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Company whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Company whereIsActive($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Company whereLogo($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Company whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Company whereTel($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Company whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Company whereUserId($value)
 * @mixin \Eloquent
 * @property-read \Illuminate\Database\Eloquent\Collection|SupplierAccessRisk[] $supplierAccessRisks
 * @property-read int|null $supplier_access_risks_count
 * @property-read \Illuminate\Database\Eloquent\Collection|SupplierAccess[] $supplierAccesses
 * @property-read int|null $supplier_accesses_count
 * @property-read \Illuminate\Database\Eloquent\Collection|Supplier[] $suppliers
 * @property-read int|null $suppliers_count
 */
class Company extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'tel',
        'about',
        'logo',
        'address',
        'currency_id',
        'is_active',
    ];
}
`

I moved class into App\Models\User and old name space is App\Models. when run command check:psr4 tell me:
```
 Checking PSR-4 Namespaces...
 - 161 namespaces were Checked!

All psr4 are correct!
```
this dockblock generated by ide-helper

**Comment by imanghafoori1** [comment]
Thanks for reporting, it is because the docblock is very big.
For now, you can see the fix on the dev-master version.
please delete and republish your config file and set the "psr4_buffer" to a higher value, after updating.
